# **ETAPAS DO PROJETO**



## Etapa 1 – Coleta de Dados (Balão 1)

In [152]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [153]:
import os

caminho = "/content/drive/MyDrive/ProjetoDados/Dados/Crimes"
print(os.listdir(caminho))

['2021.csv', '2022.csv', '2023.csv', '2024.csv', '2025.csv', '2026.csv']

Lista de arquivos coletados de crime e de clima:

In [154]:
import os

caminho_crimes = "/content/drive/MyDrive/ProjetoDados/Dados/Crimes"

arquivos_crimes = os.listdir(caminho_crimes)

print("Datasets de Criminalidade:\n")

for arquivo in arquivos_crimes:
    print(f"- {arquivo}")

Datasets de Criminalidade:

- 2021.csv
- 2022.csv
- 2023.csv
- 2024.csv
- 2025.csv
- 2026.csv

In [155]:
caminho_clima = "/content/drive/MyDrive/ProjetoDados/Dados/Clima"

arquivos_clima = os.listdir(caminho_clima)

print("\nDatasets Meteorológicos:\n")

for arquivo in arquivos_clima:
    print(f"- {arquivo}")

Datasets Meteorológicos:

- passo_fundo_2021-01-01_2025-09-05.csv

---

# Etapa 2 – Concatenação dos Dados de Criminalidade (Balão 2)

In [156]:
import pandas as pd

caminho_arquivo = "/content/drive/MyDrive/ProjetoDados/Dados/Crimes/2024.csv"

# criando uma função pra padronizar as colunas e depois aplicar em tds os csvs
def tratar_df(caminho_arquivo):

    df = pd.read_csv(caminho_arquivo, sep=';', encoding='latin1')

    df.columns = df.columns.str.lower().str.replace(' ', '_')  # colocando o nome das colunas em letra minúscula e substituindo o espaço do meio pelo underline
    df = df.loc[:, ~df.columns.str.contains('unnamed')]  # pegando só as colunas q não sao unnamed
    df = df.drop(columns=['...'], errors='ignore')  # removendo essa coluna dos tres pontinhos

    df['data_fato'] = pd.to_datetime(df['data_fato'], errors='coerce')  # mudando o tipo da coluna de data

    # mudando o tipo das colunas pra economizar memória
    colunas_categoria = [
        'grupo_fato',
        'tipo_enquadramento',
        'tipo_fato',
        'municipio_fato',
        'local_fato',
        'sexo_vítima',
        'cor_vítima'
    ]

    for col in colunas_categoria:
        df[col] = df[col].astype('category')

    # mudando o tipo das colunas de quantidade e idade pra inteiro
    df['quantidade_vítimas'] = df['quantidade_vítimas'].astype('Int64')
    df['idade_vítima'] = df['idade_vítima'].astype('Int64')

    return df

In [157]:
df_2021 = tratar_df("/content/drive/MyDrive/ProjetoDados/Dados/Crimes/2021.csv")
df_2022 = tratar_df("/content/drive/MyDrive/ProjetoDados/Dados/Crimes/2022.csv")
df_2023 = tratar_df("/content/drive/MyDrive/ProjetoDados/Dados/Crimes/2023.csv")
df_2024 = tratar_df("/content/drive/MyDrive/ProjetoDados/Dados/Crimes/2024.csv")
df_2025 = tratar_df("/content/drive/MyDrive/ProjetoDados/Dados/Crimes/2025.csv")
df_2026 = tratar_df("/content/drive/MyDrive/ProjetoDados/Dados/Crimes/2026.csv")

/tmp/ipykernel_448/2232154311.py:8: DtypeWarning: Columns (23,24,26,27,29,30,32,33,35,36,38,39,41,42,44,45,47,48,50,51,53,54,56,57,59,60,62,63,65,66,68,69,71,72,74,75,77,78,80,81,83,84,86,87,89,90,92,93,95,96,98,99,101,102,104,105,107,108,110,111,113,114,116,117,119,120,122,123,125,126,128,129,131,132,134,135) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_arquivo, sep=';', encoding='latin1')
/tmp/ipykernel_448/2232154311.py:8: DtypeWarning: Columns (0,26,27,29,30,32,33,35,36,38,39,41,42,44,45,47,48,50,51,53,54,56,57,59,60,62,63,65,66,68,69,71,72,74,75,77,78,80,81,83,84,86,87,89,90,92,93,95,96,98,99,101,102,104,105,107,108,110,111,113,114,116,117) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_arquivo, sep=';', encoding='latin1')
/tmp/ipykernel_448/2232154311.py:8: DtypeWarning: Columns (23,24,26,27,29,30,32,33,35,36,38,39,41,42,44,45,47,48,50,51,53,54,56,57,59,60,62,63,65,66,68,69,71,72,74,75,77,78,80,81,83,84,86,87,89,90,92,93,95,96,98,99,101,102,104,105,107,108,110,111,113,114,116,117,119,120,122,123) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_arquivo, sep=';', encoding='latin1')
/tmp/ipykernel_448/2232154311.py:8: DtypeWarning: Columns (23,24,26,27,29,30,32,33,35,36,38,39,41,42,44,45,47,48,50,51,53,54,56,57,59,60,62,63,65,66,68,69,71,72,74,75,77,78,80,81,83,84,86,87,89,90,92,93,95,96,98,99,101,102,104,105,107,108,110,111,113,114,116,117,119,120,122,123,125,126) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_arquivo, sep=';', encoding='latin1')
/tmp/ipykernel_448/2232154311.py:8: DtypeWarning: Columns (23,24,26,27,29,30,32,33,35,36,38,39,41,42,44,45,47,48,50,51,53,54,56,57,59,60,62,63,65,66,68,69,71,72,74,75,77,78,80,81,83,84,86,87,89,90,92,93,95,96,98,99,101,102,104,105,107,108,110,111,113,114,116,117,119,120,122,123,125,126,128,129,131,132,134,135,137,138,140,141,143,144,146,147,149,150,152,153,155,156,158,159,161,162,164,165,167,168,170,171,173,174,176,177,179,180) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_arquivo, sep=';', encoding='latin1')
/tmp/ipykernel_448/2232154311.py:8: DtypeWarning: Columns (29,30,32,33,35,36,38,39,41,42,44,45,47,48,50,51,53,54,56,57,59,60,62,63,65,66,68,69,71,72,74,75,77,78,80,81,83,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(caminho_arquivo, sep=';', encoding='latin1')

In [158]:
# pra verificar se os tipos de dados ficaram certinhos

df_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166150 entries, 0 to 166149
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   sequência           166150 non-null  int64
 1   data_fato           69256 non-null   datetime64[ns]
 2   hora_fato           166150 non-null  object
 3   grupo_fato          166150 non-null  category
 4   tipo_enquadramento  166150 non-null  category
 5   tipo_fato           166150 non-null  category
 6   municipio_fato      166150 non-null  category
 7   local_fato          166150 non-null  category
 8   bairro              132645 non-null  object
 9   quantidade_vítimas  166150 non-null  Int64
 10  idade_vítima        132008 non-null  Int64
 11  sexo_vítima         132010 non-null  category
 12  cor_vítima          132010 non-null  category
dtypes: Int64(2), category(7), datetime64[ns](1), int64(1), object(2)
memory usage: 9.4+ MB

In [159]:
# concatenando (juntando) tds os dfs de crimes

df_crimes = pd.concat([
    df_2021,
    df_2022,
    df_2023,
    df_2024,
    df_2025,
    df_2026], ignore_index=True)

In [160]:
# testando se foi td concatenado e os tipos das colunas estão certos

df_crimes.info()
df_crimes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3218268 entries, 0 to 3218267
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   sequência           object
 1   data_fato           datetime64[ns]
 2   hora_fato           object
 3   grupo_fato          object
 4   tipo_enquadramento  object
 5   tipo_fato           category
 6   municipio_fato      object
 7   local_fato          category
 8   bairro              object
 9   quantidade_vítimas  Int64
 10  idade_vítima        Int64
 11  sexo_vítima         category
 12  cor_vítima          category
dtypes: Int64(2), category(4), datetime64[ns](1), object(6)
memory usage: 239.4+ MB

,sequência,data_fato,hora_fato,grupo_fato,tipo_enquadramento,tipo_fato,municipio_fato,local_fato,bairro,quantidade_vítimas,idade_vítima,sexo_vítima,cor_vítima
0,1,2021-01-10,00:01:00,CRIMES,INCENDIO DOLOSO,Consumado,NOVA ALVORADA,RESIDENCIA,Jardim Bela Vista,1,20,Masculino,Branca
1,2,2021-01-10,00:01:00,CRIMES,VIOLENCIA PSICOLOGICA CONTRA MULHER ART 147B,Consumado,SANTA CRUZ DO SUL,RESIDENCIA,Santa Vitória,1,66,Feminino,Branca
2,3,2021-01-10,00:01:00,CRIMES,FURTO SIMPLES EM RESIDENCIA,Consumado,SANTA ROSA,RESIDENCIA,Cruzeiro,1,49,Feminino,Branca
3,4,2021-01-10,00:01:00,CRIMES,IMPORTUNACAO SEXUAL,Consumado,RIO GRANDE,VIA PUBLICA,Vila Santa Tereza,1,42,Feminino,Branca
4,5,2021-01-10,00:01:00,CRIMES,OUTRAS FRAUDES,Consumado,PORTO ALEGRE,VIA PUBLICA,Azenha,1,51,Feminino,Parda
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3218263,121878,NaT,23:50:00,CRIMES,EMBRIAGUEZ - ART. 306,Consumado,CACHOEIRINHA,VIA PUBLICA,Vl P Pora,0,<NA>,NaN,NaN
3218264,121879,NaT,23:50:00,CONTRAVENCOES,VIAS DE FATO,Consumado,CAPAO DA CANOA,RESIDENCIA,Arco Iris,1,42,Masculino,Branca
3218265,121880,NaT,23:50:00,CRIMES,AMEACA,Consumado,GUAPORE,RESIDENCIA,Planalto,1,38,Feminino,Preta
3218266,121881,NaT,23:51:00,CRIMES,FURTO/ARROMBAMENTO DE RESIDENCIA,Consumado,SAPUCAIA DO SUL,RESIDENCIA,Vargas,1,43,Masculino,Branca
3218267,121882,NaT,23:58:00,CRIMES,LESAO CORPORAL,Consumado,JAQUIRANA,ESTABELECIMENTO DIVERSAO,CENTRO,1,24,Masculino,Branca

In [161]:
df_pf = df_crimes[df_crimes["municipio_fato"] == "PASSO FUNDO"] #filtrando apenas os crimes do município de Passo Fundo
df_pf

,sequência,data_fato,hora_fato,grupo_fato,tipo_enquadramento,tipo_fato,municipio_fato,local_fato,bairro,quantidade_vítimas,idade_vítima,sexo_vítima,cor_vítima
6,7,2021-01-10,00:01:00,CRIMES,FURTO ABIGEATO,Consumado,PASSO FUNDO,OUTROS,ROD TRANSBRASILIANA,1,58,Masculino,Branca
61,65,2021-01-10,01:10:00,CRIMES,ENTORPECENTES - TRAFICO,Consumado,PASSO FUNDO,RESIDENCIA,Vila Popular,0,<NA>,NaN,NaN
67,71,2021-01-10,01:19:00,CONTRAVENCOES,VIAS DE FATO,Consumado,PASSO FUNDO,RESIDENCIA,RODRIGUEZ,1,48,Feminino,Branca
150,162,2021-01-10,03:30:09,CRIMES,FURTO DE DOCUMENTO,Consumado,PASSO FUNDO,OUTROS,Centro,1,20,Feminino,Sem informação
170,188,2021-01-10,04:14:00,CONTRAVENCOES,PERTURBACAO DO TRABALHO OU DO SOSSEGO ALHEIOS,Consumado,PASSO FUNDO,RESIDENCIA,Vila Planaltina,0,<NA>,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217845,121460,NaT,19:00:00,CRIMES,LESAO CORPORAL,Consumado,PASSO FUNDO,RESIDENCIA,Vila Vera Cruz,1,18,Feminino,Branca
3217948,121563,NaT,20:00:15,CRIMES,AMEACA,Consumado,PASSO FUNDO,OUTROS,Centro,1,39,Feminino,Sem informação
3217972,121587,NaT,20:15:02,CRIMES,AMEACA,Consumado,PASSO FUNDO,OUTROS,Vila Industrial,1,40,Feminino,Sem informação
3218110,121725,NaT,21:40:00,CRIMES,OUTROS CRIMES CONTRA A ADMINISTRACAO PUBLICA,Consumado,PASSO FUNDO,OUTROS,São Luiz Gonzaga,0,<NA>,NaN,NaN
3218231,121846,NaT,23:09:00,CRIMES,ROUBO A ESTABELECIMENTO COMERCIAL,Consumado,PASSO FUNDO,ESTABELECIMENTO COMERCIAL,NaN,1,36,Feminino,Branca

Etapa 3 – Limpeza e Padronização (Balão 3)

In [162]:
# verificando se tem coisa duplicada (já verifiquei e não tem, não precisar usar o drop!!!!)

df_pf.duplicated().sum()

np.int64(0)

In [163]:
# verificando se tem dados vazios

df_pf.isna().sum()

sequência                 0
data_fato             40196
hora_fato                 0
grupo_fato                0
tipo_enquadramento        0
tipo_fato                 0
municipio_fato            0
local_fato                0
bairro                 7498
quantidade_vítimas        0
idade_vítima           9029
sexo_vítima            9104
cor_vítima             9024
dtype: int64

In [164]:
# apagando valores nulos quando são poucos faltantes

df_pf = df_pf.dropna(subset=[
    'tipo_fato',
    'municipio_fato',
    'local_fato'
])

In [165]:
df_pf = df_pf.copy()

# alterando os valores nulos de bairro para "desconhecido"
df_pf.loc[:, 'bairro'] = df_pf['bairro'].fillna('desconhecido')

# alterando os valores nulos de sexo_vítima para "desconhecido"
if 'desconhecido' not in df_pf['sexo_vítima'].cat.categories:
    df_pf.loc[:, 'sexo_vítima'] = df_pf['sexo_vítima'].cat.add_categories('desconhecido')

df_pf.loc[:, 'sexo_vítima'] = df_pf['sexo_vítima'].fillna('desconhecido')

# alterando os valores nulos de cor_vítima para "desconhecido"
if 'desconhecido' not in df_pf['cor_vítima'].cat.categories:
    df_pf.loc[:, 'cor_vítima'] = df_pf['cor_vítima'].cat.add_categories('desconhecido')

df_pf.loc[:, 'cor_vítima'] = df_pf['cor_vítima'].fillna('desconhecido')

# idade (média inteira)
media_idade = round(df_pf["idade_vítima"].mean())

df_pf.loc[:, "idade_vítima"] = df_pf["idade_vítima"].fillna(media_idade).astype("Int64")

/tmp/ipykernel_448/2591534203.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['Masculino', NaN, 'Feminino', 'Feminino', NaN, ..., 'Feminino', 'Feminino', 'Feminino', NaN, 'Feminino']
Length: 67274
Categories (3, object): ['Feminino', 'Masculino', 'desconhecido']' has dtype incompatible with category, please explicitly cast to a compatible dtype first.
  df_pf.loc[:, 'sexo_vítima'] = df_pf['sexo_vítima'].cat.add_categories('desconhecido')
/tmp/ipykernel_448/2591534203.py:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '['Branca', NaN, 'Branca', 'Sem informação', NaN, ..., 'Branca', 'Sem informação', 'Sem informação', NaN, 'Branca']
Length: 67274
Categories (7, object): ['Amarela', 'Branca', 'Indígena', 'Parda', 'Preta', 'Sem informação',
                         'desconhecido']' has dtype incompatible with category, please explicitly cast to a compatible dtype first.
  df_pf.loc[:, 'cor_vítima'] = df_pf['cor_vítima'].cat.add_categories('desconhecido')

In [166]:
# verificando o tratamento dos dados vazios

df_pf.isna().sum()

sequência                 0
data_fato             40196
hora_fato                 0
grupo_fato                0
tipo_enquadramento        0
tipo_fato                 0
municipio_fato            0
local_fato                0
bairro                    0
quantidade_vítimas        0
idade_vítima              0
sexo_vítima               0
cor_vítima                0
dtype: int64

In [167]:
df_pf['tipo_enquadramento'].unique()

array(['FURTO ABIGEATO', 'ENTORPECENTES - TRAFICO', 'VIAS DE FATO',
       'FURTO DE DOCUMENTO',
       'PERTURBACAO DO TRABALHO OU DO SOSSEGO ALHEIOS', 'LESAO CORPORAL',
       'DESCUMPRIMENTO DE MEDIDA PROTETIVA DE URGENCIA', 'AMEACA',
       'VIOLENCIA PSICOLOGICA CONTRA MULHER ART 147B',
       'FURTO QUALIFICADO', 'ESTELIONATO', 'OUTRAS FRAUDES',
       'ADULTERACAO DE SINAL IDENTIFICADOR DE VEICULO AUTOMOTOR',
       'EXERCICIO ARBITRARIO PROPRIAS RAZOES', 'OUTROS CRIMES',
       'FURTO DE VEICULO', 'FURTO SIMPLES EM RESIDENCIA',
       'FALSIDADE IDEOLOGICA', 'DIFAMACAO',
       'VIOLAR A SUSPENSAO OU PROIBICAO DE DIRIGIR VEICULO ART.307',
       'FURTO DE FIOS E CABOS',
       'PERMITIR,CONFIAR,OU ENTREG. DIRECAO A PESSOA S/HABIL.ART 310',
       'ENTORPECENTES  POSSE', 'RESISTENCIA', 'ESTUPRO DE VULNERAVEL',
       'INJURIA', 'CRIMES DE ABUSO DE AUTORIDADE', 'DESACATO',
       'LESAO CORPORAL CULPOSA DIRECAO VEIC AUTOMOTOR',
       'FUGA DE LOCAL DE ACIDENTE - ART. 305', 'EMBRIAGUEZ - ART. 306',
       'FURTO EM VEICULO', 'OUTROS FURTOS', 'VIOLACAO DE DOMICILIO',
       'DANO', 'DISPARO DE ARMA DE FOGO', 'CRUELDADE CONTRA ANIMAIS',
       'DESOBEDIENCIA', 'ROUBO A PEDESTRE',
       'HOMICIDIO CULPOSO DIRECAO VEIC AUTOMOTOR',
       'OUTROS CRIMES QUE GERAM TERMOS CIRCUNSTANCIADOS',
       'ROUBO DE VEICULO', 'INCENDIO DOLOSO', 'FURTO/ARROMBAMENTO',
       'CRIME DE POLUICAO E OUTROS CRIMES AMBIENTAIS',
       'APROPRIACAO INDEBITA DE BEM DE IDOSO',
       'FURTO DE TELEFONE CELULAR', 'INJURIA DISCRIMINATORIA',
       'ROUBO A TRANSPORTE COLETIVO',
       'FURTO/ARROMBAMENTO ESTABELECIMENTO COMERCIAL', 'ESTUPRO',
       'PERSEGUICAO', 'RECEPTACAO DE VEICULO', 'FALSA IDENTIDADE',
       'ORGANIZACAO CRIMINOSA ART 2 DA LEI 12850 DE 2013', 'CALUNIA',
       'HOMICIDIO DOLOSO', 'FURTO/ARROMBAMENTO DE RESIDENCIA',
       'IMPORTUNACAO SEXUAL', 'OUTROS ROUBOS',
       'TRAFEGAR COM VELOCIDADE INCOMPATIVEL COM A SEGURANCA ART.311',
       'CORRUPCAO ATIVA', 'OMISSAO DE SOCORRO CONTRA O IDOSO',
       'CONCUSSAO', 'APROPRIACAO INDEBITA',
       'OUTROS CRIMES CONTRA O IDOSO', 'MAUS TRATOS',
       'DIVULGACAO DE CENA DE ESTUPRO DE SEXO OU DE PORNOGRAFIA',
       'ROUBO A ESTABELECIMENTO COMERCIAL',
       'OUTROS CRIMES CONTRA A CRIANCA/ADOLESCENTE',
       'OMISSAO SOCORRO ART 135 CP', 'DANO QUALIFICADO',
       'ABANDONO DE INCAPAZ', 'CRIMES CONTRA A FAUNA',
       'CRIMES CONTRA A FLORA', 'ATO OBSCENO',
       'PORTE ILEGAL DE ARMA DE FOGO DE USO PERMITIDO',
       'LESAO CORPORAL LEVE', 'ROUBO DE TELEFONE CELULAR',
       'ROUBO A RESIDENCIA', 'APROPRIACAO DE COISA ACHADA',
       'HOMICIDIO CULPOSO', 'ESBULHO POSSESSORIO', 'EXTORSAO',
       'COACAO NO CURSO DO PROCESSO', 'RECEPTACAO',
       'POSSE OU PORTE ILEGAL DE ARMA DE FOGO DE USO RESTRITO',
       'COMUNICACAO FALSA DE CRIME OU CONTRAVENCAO',
       'FURTO/ARROMBAMENTO A ESTABELECIMENTO DE ENSINO',
       'INCENDIO CULPOSO', 'LESAO CORPORAL CULPOSA',
       'POSSE IRREGULAR DE ARMA DE FOGO DE USO PERMITIDO',
       'ROUBO A PEDESTRE COM LESOES', 'MAUS TRATOS CONTRA O IDOSO',
       'INVASAO DE DISPOSITIVO INFORMATICO',
       'OMISSAO DE CAUTELA NA GUARDA OU CONDUCAO DE ANIMAIS',
       'DIRIGIR SEM HABILITACAO GERANDO PERIGO DE DANO ART. 309',
       'ROUBO COM LESOES', 'RIXA', 'FURTO DE ARMA', 'JOGOS DE AZAR',
       'FALSIFICACAO DE DOCUMENTOS PARTICULARES',
       'CRIMES DE LAVAGEM OU OCULTACAO DE BENS DIREITOS E VALORES LEI 9613 DE 3 DE MARCO DE 1998',
       'SERVIR BEBIDA ALCOOLICA A VULNERAVEIS',
       'DIRECAO PERIGOSA (RACHA) ART 308', 'PORTE ARMA BRANCA',
       'ROUBO DE VEICULO COM LESOES',
       'ROUBO A MOTORISTA DE CARGA DE CAMINHAO',
       'ROUBO A MOTORISTA DE CARRO ENTREGAS', 'ASSEDIO SEXUAL',
       'OUTROS CRIMES CONTRA O SENTIMENTO RELIGIOSO',
       'DENUNCIACAO CALUNIOSA',
       'OUTROS CRIMES CONTRA A INCULUMIDADE PUBLICA',
       'ROUBO A MOTORISTA PARTICULAR', 'LESAO CORPORAL GRAVE',
       'VIOLACAO DE SEPULTURA',
       'FORNECER ARMA, MUNICAO, EXPLOSIVO A CRIANCA/ADOLESCENTE',
       'ABANDONO MATERIAL', 'ASSOCIACAO CRIMINOSA ART 288 DO CP',
       'HOMICIDIO DECORRENTE DE OPOSICAO A INTERVENCAO POLICIAL',
       'EXERCICIO ARBITRARIO OU ABUSO DE PODER',
       'FURTO DE CARGA EM CAMINHAO', 'FURTO EM VEICULO - ESTEPE',
       'ABORTO', 'FURTO SIMPLES', 'ROUBO DE DOCUMENTO',
       'OUTROS CRIMES CONTRA A FE PUBLICA',
       'FEMINICIDIO ART 121 PAR 2 VI',
       'RECUSA DE DADOS SOBRE A PROPRIA IDENTIFICACAO OU QUALIFICACAO',
       'ROUBO A MOTORISTA DE TAXI', 'ROUBO A MOTORISTA COM LESOES',
       'CONSTRANGIMENTO ILEGAL DE CRIANCA E ADOLESCENTE',
       'ROUBO A RESIDENCIA COM LESOES', 'ABANDONO INTELECTUAL',
       'OUTROS CRIMES CONTRA A FAZENDA ESTADUAL', 'ROUBO A CASA LOTERICA',
       'PREVARICACAO',
       'FORNECER PRODUTOS CRIANCA/ADOLESCENTE QUE CAUSAM DEPENDENCIA',
       'CRIMES DE TORTURA   LEI 9455 DE 1997',
       'ALTERACAO LIMITES DIVISORIOS', 'LESAO CORPORAL GRAVISSIMA',
       'OUTROS CRIMES CONTRA O PATRIMONIO', 'SEQUESTRO E CARCERE PRIVADO',
       'VIOLACAO DE SIGILO FUNCIONAL', 'DISCRIMINACAO CONTRA O IDOSO',
       'EXPLORACAO SEXUAL INFANTO-JUVENIL',
       'ROUBO A ESTABELECIMENTO COMERCIAL COM LESOES',
       'CONSTRANGIMENTO ILEGAL', 'ROUBO A JOALHERIAS E OTICAS',
       'FRAUDE NO COMERCIO',
       'APROPRIACAO COISA HAVIDA POR ERRO CASO FORTUITO OU FORCA DA NATUREZA',
       'LESAO CORPORAL SEGUIDA DE MORTE',
       'OUTROS CRIMES CONTRA RELACAO DE CONSUMO EOU ECONOMIA POPULAR',
       'PICHAR OU POR OUTRO MEIO CONSPURCAR EDIFICACAO OU MONUMENTO URBANO',
       'CORRUPCAO DE MENORES',
       'CONDICIONAMENTO DE ATENDIMENTO MEDICO HOSPITALAR EMERGENCIAL',
       'ROUBO A MOTORISTA DE APLICATIVO',
       'POSSE OU PORTE ILEGAL DE ARMA DE FOGO DE USO PROIBIDO',
       'FALSO TESTEMUNHO OU FALSA PERICIA',
       'FALSIFICACAO DE PAPEIS/DOCUMENTOS PUBLICOS',
       'ROUBO DE VEICULO COM MORTE', 'ESTELIONATO  FRAUDE ELETRONICA',
       'OUTROS CRIMES CONTRA A ADMINISTRACAO PUBLICA',
       'FACILITACAO DE CONTRABANDO OU DESCAMINHO',
       'PERIGO A VIDA/SAUDE DE OUTREM', 'FURTO DE DEFENSIVO AGRICOLA',
       'EXERCICIO ILEGAL DA PROFISSAO', 'ROUBO A MALOTE', 'PECULATO',
       'HOMOFOBIA TRANSFOBIA',
       'INSERCAO DE DADOS FALSOS EM SISTEMA DE INFORMACOES',
       'PORNOGRAFIA INFANTO-JUVENIL', 'FAVORECIMENTO REAL',
       'ROUBO A ESTABELECIMENTO COMERCIAL COM MORTE',
       'INJURIA QUALIFICADA  RACA COR ETNIA RELIGIAO OU ORIGEM',
       'VIOLACAO DE CORRESPONDENCIA', 'ROUBO DE ARMA',
       'AMEACA A ESTABELECIMENTO DE ENSINO', 'PRECONCEITO RACA COR',
       'USO DE DOCUMENTO FALSO', 'OUTROS CRIMES CONTRA MEIO AMBIENTE',
       'RECEPTACAO QUALIFICADA', 'CHARLATANISMO',
       'ESTELIONATO  FRAUDE COM A UTILIZACAO DE ATIVOS VIRTUAIS VALORES MOBILIARIOS OU ATIVOS FINANCEIROS',
       'PRECONCEITO ETNIA PROCEDENCIA NACIONAL',
       'CONDUTAS RELAC. A PEDOFILIA NA INTERNET E OTR MEIOS DE COMUNIC.',
       'ROUBO A MOTORISTA DE LOTACAO', 'RECEPTACAO CULPOSA',
       'FAVORECIMENTO DA PROSTITUICAO OU DE OUTRA FORMA DE EXPLORACAO SEXUAL DE CRIANCA OU ADOLESCENTE OU DE VULNERAVEL',
       'ROUBO A PASSAGEIRO TRANSP. COLETIVO E LOTACAO',
       'ROUBO DE CELULAR', 'FURTO DE CELULAR', 'FEMINICIDIO',
       'SUBTRACAO DE INCAPAZ', 'PRECONCEITO RELIGIAO',
       'OMISSAO DE SOCORRO  ART 304 DO CTB',
       'MORTE DECORRENTE DE OPOSICAO A INTERVENCAO POLICIAL',
       'INTIMIDACAO  CYBERBULLYING',
       'DESENVOLVER OU INTRODUZIR COMANDO INSTRUO OU PROGRAMA DE COMPUTADOR CAPAZ DE DESTRUIR APAGAR ELIMINAR ALTERAR GRAVAR OU TRANSMITIR DADO INSTRUO OU PROGRAMA OU PROVOCAR QUALQUER OUTRO RESULTADO DIVERSO DO ESPERADO EM SISTEMA DE TRATAMENTO AUTOMATICO DE DADOS USADOS PELO SERVIO ELEITORAL',
       'ABANDONO DE IDOSO', 'ROUBO DE ARMA COM LESOES',
       'ENTORPECENTE  ASSOCIACAO', 'CRIME ELEITORAL',
       'EXTORSAO MEDIANTE SEQUESTRO',
       'SATISFACAO DE LASCIVIA MEDIANTE PRESENCA DE CRIANCA OU ADOLESCENTE',
       'CRIME CONTRA O SENTIMENTO RELIGIOSO E RESPEITO AOS MORTOS',
       'INTIMIDACAO  BULLYING',
       'CRIME CONTRA A ORDEM TRIBUTARIA - LEI 8137/90',
       'FURTO DE COISA COMUM ART 156  SUBTRAIR O CONDOMINO COHERDEIRO OU SOCIO PARA SI OU PARA OUTREM A QUEM LEGITIMAMENTE A DETEM A COISA COMUM',
       'NEGAR INFORMACOES AO CONSUMIDOR',
       'DESLEIXO EM INFORMACOES AO CONSUMIDOR',
       'INDUZIMENTO INSTIGAO AUXILIO AO SUICIDIO OU A AUTOMULTILAO',
       'DISPOR COISA ALHEIA COMO PROPRIA',
       'COMERCIO ILEGAL DE ARMA DE FOGO', 'ROUBO COM MORTE',
       'OMISSAO CAUTELA ARMA FOGO', 'VIOLACAO SEXUAL MEDIANTE FRAUDE',
       'FRAUDE NO PAGAMENTO POR MEIO DE CHEQUE',
       'ATENTADO CONTRA SEGURANCA SERV UTILIDADE PUBLICA',
       'CRIME CONTRA A ADMINISTRACAO AMBIENTAL', 'ABUSO DE INCAPAZ',
       'PRECONCEITO DEFICIENCIA', 'APROPRIACAO INDEBITA DE CELULAR',
       'FURTO/ARROMBAMENTO ESTABELECIMENTO BANCARIO',
       'FALSIFICAO DE MEDICAMENTO  ART 273 CP',
       'MAUS TRATOS CONTRA ANIMAIS', 'APOLOGIA DE CRIME OU CRIMINOSO',
       'CORRUPCAO PASSIVA', 'PROPAGANDA ENGANOSA'], dtype=object)

In [168]:
# corrigindo inconsistências nas colunas de forma geral

import unicodedata

# função pra transformar tudo em minúsculo, tirar espaços extras e remover acentos

def normalizar(texto):
    if pd.isna(texto):
        return texto
    texto = texto.lower().strip()
    return unicodedata.normalize('NFKD', texto).encode('ascii', 'ignore').decode('utf-8')

# aplicando a função nas colunas
colunas_categoria = [
    'grupo_fato',
    'tipo_enquadramento',
    'tipo_fato',
    'municipio_fato',
    'local_fato',
    'sexo_vítima',
    'cor_vítima'
]

for col in colunas_categoria:
    df_pf[col] = df_pf[col].apply(normalizar)

# apagando as linhas onde não constam a data do crime

df_pf = df_pf.dropna(subset=['data_fato'])

In [169]:
df_pf.isna().sum()

sequência             0
data_fato             0
hora_fato             0
grupo_fato            0
tipo_enquadramento    0
tipo_fato             0
municipio_fato        0
local_fato            0
bairro                0
quantidade_vítimas    0
idade_vítima          0
sexo_vítima           0
cor_vítima            0
dtype: int64

In [170]:
crimes_homicidio = [
    'homicidio doloso',
    'homicidio culposo',
    'homicidio culposo direcao veic automotor',
    'feminicidio',
    'feminicidio art 121 par 2 vi'
]

df_pf_homicidios = df_pf[df_pf['tipo_enquadramento'].isin(crimes_homicidio)]

# Etapa 4 – Integração com Dados Meteorológicos (Balão 4)

In [171]:
# importar o dataset meteorológico
df_clima = pd.read_csv(
    "/content/drive/MyDrive/ProjetoDados/Dados/Clima/passo_fundo_2021-01-01_2025-09-05.csv",
    encoding='latin1',
    sep=';',
    skiprows=10
)

In [172]:
# visualização do dataset de clima
df_clima.head()
df_clima.info()
df_clima.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1709 entries, 0 to 1708
Data columns (total 7 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Data Medicao                                   1709 non-null   object
 1   PRECIPITACAO TOTAL, DIARIO (AUT)(mm)           1644 non-null   object
 2   TEMPERATURA MAXIMA, DIARIA (AUT)(Â°C)          1662 non-null   object
 3   TEMPERATURA MINIMA, DIARIA (AUT)(Â°C)          1660 non-null   object
 4   UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)  1677 non-null   object
 5   VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)      1649 non-null   object
 6   Unnamed: 6                                     0 non-null      float64
dtypes: float64(1), object(6)
memory usage: 93.6+ KB

Index(['Data Medicao', 'PRECIPITACAO TOTAL, DIARIO (AUT)(mm)',
       'TEMPERATURA MAXIMA, DIARIA (AUT)(Â°C)',
       'TEMPERATURA MINIMA, DIARIA (AUT)(Â°C)',
       'UMIDADE RELATIVA DO AR, MEDIA DIARIA (AUT)(%)',
       'VENTO, VELOCIDADE MEDIA DIARIA (AUT)(m/s)', 'Unnamed: 6'],
      dtype='object')

In [173]:
# remove coluna 6 unnamed
df_clima.drop(columns=['Unnamed: 6'], inplace=True)

In [174]:
# renomeia colunas
df_clima.columns = [
    'data',
    'precipitacao',
    'temp_max',
    'temp_min',
    'umidade',
    'vento'
]

In [175]:
# ajusta data que estava como Dtype object
df_clima['data'] = pd.to_datetime(
    df_clima['data'],
    dayfirst=True,
    format='mixed',
    errors='coerce'
)
df_clima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1709 entries, 0 to 1708
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   data          1709 non-null   datetime64[ns]
 1   precipitacao  1644 non-null   object
 2   temp_max      1662 non-null   object
 3   temp_min      1660 non-null   object
 4   umidade       1677 non-null   object
 5   vento         1649 non-null   object
dtypes: datetime64[ns](1), object(5)
memory usage: 80.2+ KB

In [176]:
# converte essas colunas para numero
cols = ['precipitacao', 'temp_max', 'temp_min', 'umidade', 'vento']

for col in cols:
    df_clima[col] = pd.to_numeric(df_clima[col], errors='coerce')
df_clima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1709 entries, 0 to 1708
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   data          1709 non-null   datetime64[ns]
 1   precipitacao  1095 non-null   float64
 2   temp_max      175 non-null    float64
 3   temp_min      180 non-null    float64
 4   umidade       238 non-null    float64
 5   vento         167 non-null    float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 80.2 KB

In [177]:
# valores ausentes foram preenchidos, visto que o clima de ontem ou de amanhã é parecido
df_clima.fillna(method='ffill', inplace=True)
df_clima.fillna(method='bfill', inplace=True)
df_clima.isnull().sum()

/tmp/ipykernel_448/2157838259.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_clima.fillna(method='ffill', inplace=True)
/tmp/ipykernel_448/2157838259.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_clima.fillna(method='bfill', inplace=True)

data            0
precipitacao    0
temp_max        0
temp_min        0
umidade         0
vento           0
dtype: int64

In [178]:
# Padronizar a data
df_pf_homicidios['data'] = pd.to_datetime(df_pf_homicidios['data_fato']).dt.normalize()
df_clima['data'] = pd.to_datetime(df_clima['data']).dt.normalize()

/tmp/ipykernel_448/2686338825.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pf_homicidios['data'] = pd.to_datetime(df_pf_homicidios['data_fato']).dt.normalize()

In [179]:
# Cria coluna cidade igual para os dois

df_pf_homicidios['cidade'] = 'passo fundo'
df_clima['cidade'] = 'passo fundo'

/tmp/ipykernel_448/85754877.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pf_homicidios['cidade'] = 'passo fundo'

In [180]:
# faz o merge entre clima e crimes
df_final = pd.merge(
    df_pf_homicidios,
    df_clima,
    on=['data', 'cidade'],
    how='left'
)
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sequência           135 non-null    object
 1   data_fato           135 non-null    datetime64[ns]
 2   hora_fato           135 non-null    object
 3   grupo_fato          135 non-null    object
 4   tipo_enquadramento  135 non-null    object
 5   tipo_fato           135 non-null    category
 6   municipio_fato      135 non-null    object
 7   local_fato          135 non-null    category
 8   bairro              135 non-null    object
 9   quantidade_vítimas  135 non-null    Int64
 10  idade_vítima        135 non-null    Int64
 11  sexo_vítima         135 non-null    category
 12  cor_vítima          135 non-null    category
 13  data                135 non-null    datetime64[ns]
 14  cidade              135 non-null    object
 15  precipitacao        125 non-null    float64
 16  temp_max            125 non-null    float64
 17  temp_min            125 non-null    float64
 18  umidade             125 non-null    float64
 19  vento               125 non-null    float64
dtypes: Int64(2), category(4), datetime64[ns](2), float64(5), object(7)
memory usage: 18.7+ KB

In [181]:
df_final.head()

,sequência,data_fato,hora_fato,grupo_fato,tipo_enquadramento,tipo_fato,municipio_fato,local_fato,bairro,quantidade_vítimas,idade_vítima,sexo_vítima,cor_vítima,data,cidade,precipitacao,temp_max,temp_min,umidade,vento
0,5446,2021-03-10,15:50:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,hospitais/clinicas,Centro,1,28,masculino,branca,2021-03-10,passo fundo,0.0,28.0,12.0,86.0,3.0
1,5789,2021-03-10,19:30:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,via publica,desconhecido,1,20,masculino,branca,2021-03-10,passo fundo,0.0,28.0,12.0,86.0,3.0
2,12890,2021-07-10,09:15:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,via publica,desconhecido,1,41,masculino,branca,2021-07-10,passo fundo,0.0,17.0,9.0,74.0,4.0
3,14396,2021-07-10,21:00:00,crimes,homicidio doloso,consumado,passo fundo,residencia,integraçao,1,29,feminino,parda,2021-07-10,passo fundo,0.0,17.0,9.0,74.0,4.0
4,16327,2021-08-10,18:30:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,via publica,Petropolis,1,28,masculino,branca,2021-08-10,passo fundo,9.0,14.0,12.0,68.0,3.0

In [182]:
# irá remover as linhas que não tiveram clima
df_final = df_final.dropna(subset=['precipitacao', 'temp_max', 'temp_min', 'umidade', 'vento'])

In [183]:
# verifica se nenhuma coluna gerou dados vazios
df_final.isnull().sum()

sequência             0
data_fato             0
hora_fato             0
grupo_fato            0
tipo_enquadramento    0
tipo_fato             0
municipio_fato        0
local_fato            0
bairro                0
quantidade_vítimas    0
idade_vítima          0
sexo_vítima           0
cor_vítima            0
data                  0
cidade                0
precipitacao          0
temp_max              0
temp_min              0
umidade               0
vento                 0
dtype: int64

In [184]:
# verificando se as colunas de data e cidade possuem as mesmas infos de data_fato e municipio_fato, pra depois excluir

(df_final['municipio_fato'] == df_final['cidade']).all()
(df_final['data_fato'] == df_final['data']).all()

np.True_

In [185]:
# como as informações das colunas são iguais, vou apagar data e cidade pra evitar duplicidade
# para deixar o df mais limpo, vou excluir a coluna "sequência", "local_fato" e "bairro", por não possuírem relevância para a nossa análise
df_final = df_final.drop(columns=['data', 'cidade', 'sequência', 'local_fato', 'bairro'])

In [186]:
# a fim de melhor visualização, vou criar a coluna "chuva" pra verificar se choveu ou não no dia em que o crime ocorreu. Acho que apenas "precipitacao" em número não deixa muito claro.
# se a precipitação for maior que zero, significa que houve chuva e na coluna deve constar "sim"

df_final['chuva'] = (df_final['precipitacao'] > 0).map({True: 'Sim', False: 'Não'})

In [187]:
df_final

,data_fato,hora_fato,grupo_fato,tipo_enquadramento,tipo_fato,municipio_fato,quantidade_vítimas,idade_vítima,sexo_vítima,cor_vítima,precipitacao,temp_max,temp_min,umidade,vento,chuva
0,2021-03-10,15:50:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,1,28,masculino,branca,0.0,28.0,12.0,86.0,3.0,Não
1,2021-03-10,19:30:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,1,20,masculino,branca,0.0,28.0,12.0,86.0,3.0,Não
2,2021-07-10,09:15:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,1,41,masculino,branca,0.0,17.0,9.0,74.0,4.0,Não
3,2021-07-10,21:00:00,crimes,homicidio doloso,consumado,passo fundo,1,29,feminino,parda,0.0,17.0,9.0,74.0,4.0,Não
4,2021-08-10,18:30:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,1,28,masculino,branca,9.0,14.0,12.0,68.0,3.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,2025-07-05,16:15:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,2,43,masculino,branca,0.0,16.0,-1.0,95.0,2.0,Não
127,2025-07-07,06:50:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,1,71,feminino,branca,0.0,16.0,-1.0,95.0,2.0,Não
128,2025-06-09,11:30:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,5,63,feminino,branca,0.0,16.0,13.0,91.0,2.0,Não
130,2025-02-11,02:40:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,1,51,feminino,sem informacao,0.0,32.0,21.0,68.0,3.0,Não
131,2025-07-11,01:00:00,crimes,homicidio doloso,consumado,passo fundo,1,44,masculino,parda,0.0,16.0,-1.0,71.0,2.0,Não

Foi realizada a integração entre os dados de criminalidade e os dados meteorológicos utilizando as colunas data e cidade como chave de junção, considerando o município de Passo Fundo.

Inicialmente, o dataset meteorológico apresentava valores ausentes nas variáveis climáticas (precipitação, temperatura, umidade e vento). Esses valores foram tratados utilizando as técnicas de forward fill e backward fill, assumindo que as condições climáticas variam de forma gradual entre dias consecutivos.

Após o merge, alguns registros permaneceram com valores ausentes nas variáveis climáticas devido à inexistência de dados meteorológicos para determinadas datas no período analisado.

Os dados de criminalidade não foram alterados, pois representam eventos reais e não devem ser estimados ou preenchidos artificialmente.

Dessa forma, optou-se por remover apenas os registros que não possuíam informações meteorológicas correspondentes, garantindo a consistência e a confiabilidade do dataset final.

Assim, obteve-se um dataset unificado contendo variáveis de criminalidade e clima, sem valores nulos nas colunas meteorológicas.

# Etapa 5 – Transformações (Balão 5)

In [188]:
# Como não vou trabalhar com muitas das colunas categóricas, para melhor visualização do dataset vou optar por deixá-las como categoria mesmo

# A coluna de chuva também já foi criada com o intuito de facilitar a visualização da precipitação, que antes era apenas numérica e pouco legível

# Para reduzir ruído, vou unificar em "tipo_enquadramento" o 'feminicidio' e 'feminicidio art 121 par 2 vi' pois são a mesma coisa

# Assim, localizo todas as linhas que contém a palavra feminicidio e substituo o valor inteiro da célula por apenas "feminicidio"

df_final.loc[
    df_final['tipo_enquadramento'].str.contains('feminicidio'),
    'tipo_enquadramento'
] = 'feminicidio'

In [189]:
# Quanto aos outliers, vou verificar referente as idades das vítimas, pelo IQR

Q1 = df_final['idade_vítima'].quantile(0.25)
Q3 = df_final['idade_vítima'].quantile(0.75)
IQR = Q3 - Q1

limite_superior = Q3 + 1.5 * IQR
limite_inferior = Q1 - 1.5 * IQR

print(Q1, Q3, IQR)
print(limite_superior, limite_inferior)

# pra visualizar os outliers

outliers = df_final[
    (df_final['idade_vítima'] < limite_inferior) |
    (df_final['idade_vítima'] > limite_superior)
]

outliers

# Como não obtive nenhum resultado fora dos limites, verifiquei que não existem outliers na idade das vítimas

26.0 51.0 25.0
88.5 -11.5

Empty DataFrame
Columns: [data_fato, hora_fato, grupo_fato, tipo_enquadramento, tipo_fato, municipio_fato, quantidade_vítimas, idade_vítima, sexo_vítima, cor_vítima, precipitacao, temp_max, temp_min, umidade, vento, chuva]
Index: []

In [190]:
# para fins de padronização, vou remover os acentos nos nomes das colunas novamente, usando a função que já havia criado na etapa 3

df_final.columns = [normalizar(col) for col in df_final.columns]
df_final

# Quanto à normalização, optei por não fazer pq meus dados perderiam o sentido e dificultaria muito a interpretação. Como o objetivo do trabalho é fazer uma análise, não cabe aqui normalizar informações como idade, temperatura e etc

,data_fato,hora_fato,grupo_fato,tipo_enquadramento,tipo_fato,municipio_fato,quantidade_vitimas,idade_vitima,sexo_vitima,cor_vitima,precipitacao,temp_max,temp_min,umidade,vento,chuva
0,2021-03-10,15:50:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,1,28,masculino,branca,0.0,28.0,12.0,86.0,3.0,Não
1,2021-03-10,19:30:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,1,20,masculino,branca,0.0,28.0,12.0,86.0,3.0,Não
2,2021-07-10,09:15:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,1,41,masculino,branca,0.0,17.0,9.0,74.0,4.0,Não
3,2021-07-10,21:00:00,crimes,homicidio doloso,consumado,passo fundo,1,29,feminino,parda,0.0,17.0,9.0,74.0,4.0,Não
4,2021-08-10,18:30:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,1,28,masculino,branca,9.0,14.0,12.0,68.0,3.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,2025-07-05,16:15:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,2,43,masculino,branca,0.0,16.0,-1.0,95.0,2.0,Não
127,2025-07-07,06:50:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,1,71,feminino,branca,0.0,16.0,-1.0,95.0,2.0,Não
128,2025-06-09,11:30:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,5,63,feminino,branca,0.0,16.0,13.0,91.0,2.0,Não
130,2025-02-11,02:40:00,crimes,homicidio culposo direcao veic automotor,consumado,passo fundo,1,51,feminino,sem informacao,0.0,32.0,21.0,68.0,3.0,Não
131,2025-07-11,01:00:00,crimes,homicidio doloso,consumado,passo fundo,1,44,masculino,parda,0.0,16.0,-1.0,71.0,2.0,Não

In [191]:
# Salvando o df final em um arquivo csv para entrega

df_final.to_csv('df_final.csv', index=False, encoding='utf-8')

Foram realizadas padronizações no dataset para melhorar a qualidade e facilitar a análise. As categorias da coluna tipo_enquadramento foram unificadas (como os casos de feminicídio), reduzindo inconsistências. Também foi feita a remoção de acentos nos nomes das colunas para manter um padrão.

Em relação aos outliers, foi aplicada a técnica de IQR na variável idade das vítimas, e não foram identificados valores fora dos limites, indicando ausência de outliers.

A normalização dos dados não foi realizada, pois poderia prejudicar a interpretação dos valores no contexto da análise.